[project]
site_name = "韭韭归一：老亢给小白的投基兵法"
site_url = "https://invest.brainz.fun/"
docs_dir = "docs"

nav = [
    { "简介" = "index.md" },
    { "序言" = "00_序言.md" },
    { "第一回" = "01_第一回.md" },
    { "第二回" = "02_第二回.md" },
    { "第三回" = "03_第三回.md" },
    { "第四回" = "04_第四回.md" },
    { "第五回" = "05_第五回.md" },
    { "第六回" = "06_第六回.md" },
    { "第七回" = "07_第七回.md" },
    { "第八回" = "08_第八回.md" },
    { "结语" = "09_结语.md" }
]

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

